//! Agent layout intent - minimal output from AI agent.
//!
//! Agent only outputs indices and layout decisions, never actual data.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// AI Agent layout decision - minimal, index-based.
///
/// # Zero Hallucination Guarantee
/// - Agent outputs `selected_data_index` (integer reference)
/// - Actual data comes from tool_steps, not generated by agent
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct AgentLayoutIntent {
    /// Explanation of layout choice (can be empty)
    pub analysis_text: String,

    /// Index into tool_steps array (zero-based)
    pub selected_data_index: usize,

    /// Component type from ui.toml (e.g. "product_card")
    pub component_type: String,

    /// Layout direction: "horizontal" or "vertical"
    pub layout_direction: String,

    /// Card position: "left", "right", "top", or "bottom"
    pub card_position: String,
}

impl AgentLayoutIntent {
    /// Check if card should be first in layout order.
    pub fn card_first(&self) -> bool {
        matches!(self.card_position.as_str(), "left" | "top")
    }

    /// Check if layout is horizontal.
    pub fn is_horizontal(&self) -> bool {
        self.layout_direction == "horizontal"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_intent_deserialization() {
        let json = r#"{
            "analysisText": "Great product recommendation",
            "selectedDataIndex": 0,
            "componentType": "product_card",
            "layoutDirection": "horizontal",
            "cardPosition": "left"
        }"#;

        let intent: AgentLayoutIntent = serde_json::from_str(json).unwrap();
        assert_eq!(intent.analysis_text, "Great product recommendation");
        assert_eq!(intent.selected_data_index, 0);
        assert_eq!(intent.component_type, "product_card");
        assert!(intent.card_first());
        assert!(intent.is_horizontal());
    }

    #[test]
    fn test_card_position() {
        let intent = AgentLayoutIntent {
            analysis_text: String::new(),
            selected_data_index: 0,
            component_type: "text".into(),
            layout_direction: "vertical".into(),
            card_position: "bottom".into(),
        };

        assert!(!intent.card_first());
        assert!(!intent.is_horizontal());
    }
}
