default_provider = "gemini"
model = "gemini-2.5-flash"

prompt_template = """
Anda adalah petugas Pelayanan Publik Kelurahan Cakung Barat. Sapa warga dengan hangat, jelaskan prosedur administratif dengan jelas, dan pastikan mereka mengetahui dokumen atau langkah yang harus ditempuh.

{{custom_instruction}}

{{language_guidance}}

{{tool_guidance}}

Utamakan solusi praktis, ringkas poin penting dalam bentuk daftar bila diperlukan, dan tutup dengan menawarkan bantuan lanjutan bila masih ada kendala.
"""

[[providers]]
id = "gemini"
type = "gemini"
endpoint = "https://generativelanguage.googleapis.com"
api_key = "GEMINI_API_KEY"
models = [
    { name = "gemini-2.5-flash", display_name = "Gemini 2.5 Flash" },
    { name = "gemini-2.5-flash-exp", display_name = "Gemini 2.5 Flash Exp" },
    { name = "gemini-2.0-flash-lite", display_name = "Gemini 2.0 Flash Lite" },
    { name = "gemini-2.0-flash", display_name = "Gemini 2.0 Flash" },
    { name = "gemini-2.5-flash-lite", display_name = "Gemini 2.5 Flash Lite" },
    { name = "gemini-2.5-flash-tts", display_name = "Gemini 2.5 Flash TTS" },
    { name = "gemini-2.5-pro", display_name = "Gemini 2.5 Pro" }
]

[[providers]]
id = "ollama"
type = "ollama"
endpoint = "http://127.0.0.1:11434"
models = [
    { name = "gemma3:4b", display_name = "Gemma 3 4B" }
]

[[servers]]
name = "time"
command = 'C:\Users\teuku\Desktop\Project\CBT\MCP\mcp-server-time\target\release\mcp-server-time.exe'
default_timezone = "Asia/Jakarta"
default_city = "Jakarta"

[[servers]]
name = "certificate"
command = 'C:\Users\teuku\Desktop\Project\CBT\MCP\cbt-mcp-server-certificate\target\release\cbt-mcp-server-certificate.exe'

[[tools]]
name = "get_current_time"
description = "WAJIB panggil di awal percakapan untuk menentukan sapaan (pagi/siang/sore/malam) dan informasi jam yang akurat, sebelum menjawab pertanyaan warga."
server = "time"

[[tools]]
name = "generate_surat_keterangan_domisili"
description = "Buat surat keterangan domisili dalam bentuk PDF berdasarkan data warga."
server = "certificate"
